### ISSUE TITLE
zip file from github fails to download (fails to follow HTTP 302?)

### ISSUE THREAD

**Issue by proycon** [KnowledgeCaptureAndDiscovery/somef#353] opened 2022-02-21 17:52 UTC
```
$ somef describe -r https://github.com/proycon/analiticcl -c /tmp/test.json -t 0.8
SOftware Metadata Extraction Framework (SOMEF) Command Line Interface
Loading Repository https://github.com/proycon/analiticcl Information....
https://api.github.com/repos/proycon/analiticcl
Downloading https://github.com/proycon/analiticcl/archive/master.zip
Traceback (most recent call last):
  File "/tmp/env/bin/somef", line 8, in <module>
    sys.exit(cli())
  File "/tmp/env/lib/python3.10/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/env/lib/python3.10/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/tmp/env/lib/python3.10/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/env/lib/python3.10/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/env/lib/python3.10/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/env/lib/python3.10/site-packages/somef/__main__.py", line 128, in describe
    cli.run_cli(**kwargs)
  File "/tmp/env/lib/python3.10/site-packages/somef/cli.py", line 1673, in run_cli
    repo_data = cli_get_data(threshold, ignore_classifiers, repo_url=repo_url)
  File "/tmp/env/lib/python3.10/site-packages/somef/cli.py", line 1564, in cli_get_data
    text, github_data = load_repository_metadata(repo_url, header)
  File "/tmp/env/lib/python3.10/site-packages/somef/cli.py", line 313, in load_repository_metadata
    with zipfile.ZipFile(repo_zip_file, "r") as zip_ref:
  File "/usr/lib/python3.10/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Same error with your example repository from the README. Running somef 0.7.0 from pypi.

**Comment by dgarijo** [comment] 2022-02-21 18:03
Hi @proycon,
this is odd, I cannot reproduce this issue. I ran the the above command and got the attached result.
My Python version is `Python 3.9.7`.

[test.json.txt](https://github.com/KnowledgeCaptureAndDiscovery/somef/files/8111325/test.json.txt)

**Comment by dgarijo** [comment] 2022-02-21 18:07
You seem to be running somef on Python 3.10. This has not been tested yet. I suggest giving a try to the Docker image in the meantime.

**Comment by proycon** [comment] 2022-02-22 11:58
Hmm right, I see it's quite explicitly tied to Python 3.9 even (pip install refused on another system with 3.8).  I assume you're using some features that were not present prior to 3.9? 

Still a bit surprising that 3.10 fails, something must have changed in the standard library since 3.9 then..

**Comment by dgarijo** [comment] 2022-02-22 12:02
We are using Scikitlearn 1.0, which was released for 3.9 and not the previous versions. Since models trained with one version are not recommended to be used with another one, we decided to support 3.9.

I don't know what could have happened in 3.10, it is quite annoying. We will look at it, but I would rather prioritize other issues right now. I will keep this one open until we have the bandwidth to support multiple Python versions

**Comment by proycon** [comment] 2022-02-22 12:30
I'm debugging a bit and it seems I simply get a HTTP 401 response (see PR above), I notice that code path doesn't pass through the rate limiting function (although I can't yet get it to work with it either or if I manually sleep 5 seconds before). So I'm not sure this is technically a Python 3.9 vs 3.10 issue anymore.

**Comment by dgarijo** [comment] 2022-02-22 13:38
Thanks for having a look.
Did the Docker image work for you? I tested it out successfully.
We tested somef in 2 machines with Python 3.9 (@ma-garcia works on Windows, and I on Unix, plus Docker). We are working on other issues which are more urgent right now, but if you provide details on how to reproduce this on Python 3.9, we will raise its priority.

**Comment by dgarijo** [comment] 2022-05-09 16:58
I installed somef in Python 3.10, and everything seems to work file (python 3.10.4). Hence I am closing this issue.

**Closed by dgarijo** 2022-05-09 16:58 UTC
Labels: bug
