### ISSUE TITLE
Error in repos from oeg-upm

### ISSUE THREAD

**Issue by dakixr** [KnowledgeCaptureAndDiscovery/somef#443] opened 2022-04-28 12:21 UTC
Env:
- Python 3.9
- somef 0.8.0

The following repos break SOMEF:
- https://github.com/oeg-upm/FarolAppsWeb
- https://github.com/oeg-upm/mappingpedia-engine-commons
- https://github.com/oeg-upm/pcake
- https://github.com/oeg-upm/epw2rdf
- https://github.com/oeg-upm/epw2rdf-contents
- https://github.com/oeg-upm/OnToologyDnD
- https://github.com/oeg-upm/awesome-semantic-web
- https://github.com/oeg-upm/kehio

**Comment by dgarijo** [comment] 2022-04-28 13:55
@dakixr it would be great if you could provide a snapshot of the error each of them produced (given that I cannot reproduce some of them)

**Comment by dakixr** [comment] 2022-04-28 15:39
Some of the errors weren't the fault of somef, the updated list:

- https://github.com/oeg-upm/awesome-semantic-web
- https://github.com/oeg-upm/epw2rdf
- https://github.com/oeg-upm/epw2rdf-contents
- https://github.com/oeg-upm/FarolAppsWeb
- https://github.com/oeg-upm/kehio
- https://github.com/oeg-upm/OnToologyDnD
- https://github.com/oeg-upm/pcake
- https://github.com/oeg-upm/SOMEF-server

Tracebacks:

```
Traceback (most recent call last):
  File "/Users/dakixr/Desktop/github/scc/src/scc/commands/extract_metadata.py", line 31, in fetch
    metadata = cli_get_data(0.9, False, repo_url)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 686, in cli_get_data
    predictions = classify(score_dict, threshold, excerpts_headers, header_parents)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 206, in classify
    'parentHeader': header_parents[header]})
KeyError: 'Awesome Semantic Web <a href="https://github.com/sindresorhus/awesome"><img alt="Awesome" src="https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg" /></a>'

Extracting metadata from https://github.com/oeg-upm/awesome-semantic-web
ERROR: Could not extract metadata from https://github.com/oeg-upm/awesome-semantic-web
```

_______________________________________________

```
Traceback (most recent call last):
  File "/Users/dakixr/Desktop/github/scc/src/scc/commands/extract_metadata.py", line 31, in fetch
    metadata = cli_get_data(0.9, False, repo_url)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 686, in cli_get_data
    predictions = classify(score_dict, threshold, excerpts_headers, header_parents)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 219, in classify
    'parentHeader': header_parents[header]})
KeyError: '**Install libraries for Python3** <h2>'

Extracting metadata from https://github.com/oeg-upm/epw2rdf
ERROR: Could not extract metadata from https://github.com/oeg-upm/epw2rdf
```

_______________________________________________

```
Traceback (most recent call last):
  File "/Users/dakixr/Desktop/github/scc/src/scc/commands/extract_metadata.py", line 31, in fetch
    metadata = cli_get_data(0.9, False, repo_url)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 686, in cli_get_data
    predictions = classify(score_dict, threshold, excerpts_headers, header_parents)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 219, in classify
    'parentHeader': header_parents[header]})
KeyError: '**Install libraries for Python3** <h2>'

Extracting metadata from https://github.com/oeg-upm/epw2rdf-contents
ERROR: Could not extract metadata from https://github.com/oeg-upm/epw2rdf-contents
```

_______________________________________________

```
Traceback (most recent call last):
  File "/Users/dakixr/Desktop/github/scc/src/scc/commands/extract_metadata.py", line 31, in fetch
    metadata = cli_get_data(0.9, False, repo_url)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 686, in cli_get_data
    predictions = classify(score_dict, threshold, excerpts_headers, header_parents)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 206, in classify
    'parentHeader': header_parents[header]})
KeyError: '3) Compile <a name="compile"></a>'

Extracting metadata from https://github.com/oeg-upm/FarolAppsWeb
ERROR: Could not extract metadata from https://github.com/oeg-upm/FarolAppsWeb
```

_______________________________________________

```
Traceback (most recent call last):
  File "/Users/dakixr/Desktop/github/scc/src/scc/commands/extract_metadata.py", line 31, in fetch
    metadata = cli_get_data(0.9, False, repo_url)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 686, in cli_get_data
    predictions = classify(score_dict, threshold, excerpts_headers, header_parents)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 206, in classify
    'parentHeader': header_parents[header]})
KeyError: '1.1  Datatype property (<a href="">code sample</a>)'

Extracting metadata from https://github.com/oeg-upm/kehio
ERROR: Could not extract metadata from https://github.com/oeg-upm/kehio

```
_______________________________________________

```
Traceback (most recent call last):
  File "/Users/dakixr/Desktop/github/scc/src/scc/commands/extract_metadata.py", line 31, in fetch
    metadata = cli_get_data(0.9, False, repo_url)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 686, in cli_get_data
    predictions = classify(score_dict, threshold, excerpts_headers, header_parents)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 219, in classify
    'parentHeader': header_parents[header]})
KeyError: '<img alt="alt text" src="WebContent/static/images/logoprop.png" title="OnToology" />'

Extracting metadata from https://github.com/oeg-upm/OnToologyDnD
ERROR: Could not extract metadata from https://github.com/oeg-upm/OnToologyDnD
```

_______________________________________________

```
Traceback (most recent call last):
  File "/Users/dakixr/Desktop/github/scc/src/scc/commands/extract_metadata.py", line 31, in fetch
    metadata = cli_get_data(0.9, False, repo_url)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/cli.py", line 701, in cli_get_data
    logo, images = regular_expressions.extract_images(unfiltered_text, repo_url, local_repo)
  File "/Users/dakixr/Desktop/github/scc/env-scc/lib/python3.9/site-packages/somef/regular_expressions.py", line 246, in extract_images
    start = img.rindex("/")
ValueError: substring not found

Extracting metadata from https://github.com/oeg-upm/pcake
ERROR: Could not extract metadata from https://github.com/oeg-upm/pcake
```

**Comment by dgarijo** [comment] 2022-04-28 16:03
It's weird, I am unable to reproduce some of these errors. How are you running this?
```somef describe -r https://github.com/oeg-upm/kehio -o out.json -t 0.95``` seems to be all right, for instance

**Comment by dgarijo** [comment] 2022-04-28 16:05
https://github.com/oeg-upm/SOMEF-server does not seem to exist, not sure why is it returned

**Comment by dgarijo** [comment] 2022-04-28 16:09
@ma-garcia please double check the problematic repos. I get an error with OnToology DnD and FarolApp (I have not tested all the others)

**Comment by dakixr** [comment] 2022-04-28 16:19
> It's weird, I am unable to reproduce some of these errors. How are you running this? `somef describe -r https://github.com/oeg-upm/kehio -o out.json -t 0.95` seems to be all right, for instance

I call somef from code instead of the CLI:

```python
from somef.cli import cli_get_data
metadata = cli_get_data(0.9, False, repo_url)
```

**Comment by dgarijo** [comment] 2022-04-28 16:45
I cannot reproduce the error with some repos, so we will focus on the ones with the error. Maybe the latest commits fixed a few of the problems.

**Comment by dgarijo** [comment] 2022-05-10 10:50
Should be fixed now

**Closed by dgarijo** 2022-05-10 10:50 UTC
Labels: bug, high_priority
