### ISSUE TITLE
Provide related_papers as a new output categorie

### ISSUE THREAD

**Issue by Ardark27** [KnowledgeCaptureAndDiscovery/somef#552] opened 2023-02-27 16:02 UTC
Provide a new categorie:

- **related_papers**: Pointers to **arxiv/doi links** found in repos.

Examples:
1.- 
repo: https://github.com/wuzhy1ng/blockchainspider
related_papers: [https://arxiv.org/abs/2201.05757]

2.-
repo: https://github.com/robbie-xu/cpsd
related_papers: [https://arxiv.org/abs/2205.10986]

3.-
repo: https://github.com/tensorflow/tensor2tensor
related_papers: [https://arxiv.org/abs/1812.02825, https://arxiv.org/abs/1706.03762,https://arxiv.org/abs/1803.07416, http://arxiv.org/abs/1803.07416, https://arxiv.org/abs/1706.03762, https://arxiv.org/abs/1706.03059, https://arxiv.org/abs/1706.05137.... ]

**Comment by dgarijo** [comment] 2023-02-27 16:19
+1. Also if we have something like cite and paper in the proximity of the link we should try and propose it as a citation.
In the third case, the problem is that the paper has a URL instead of a DOI. We could use that.

**Comment by dgarijo** [comment] 2023-06-26 09:08
Fixed by https://github.com/KnowledgeCaptureAndDiscovery/somef/pull/573

**Closed by dgarijo** 2023-06-26 09:08 UTC
Labels: enhancement, high_priority
